fix(varname): rename session variable
jwelker110/cordova-plugin-ios-aswebauthenticationsession-api pull request #2
Opened 2020-03-22 16:37 UTC by petergrau

Will avoid duplicate symbols error when used with cordova-plugin-sfauthenticationsession

If you are also using the cordova-plugin-sfauthenticationsession you will get an error for duplicate symbols. It was fixed in another fork but unfortunately that PR never got merged. RasimKanca/cordova-plugin-aswebauthenticationsession@9b12c34

mochini/cordova-plugin-aswebauthenticationsession#2

2020-03-22 17:42 UTC, jwelker110 requested changes
Thank you for taking the time to create the issue and PR, I appreciate it! Do you mind renaming it to _asAuthenticationVC?

Again, thank you for taking the time to improve the plugin.

2020-03-23 13:41 UTC, petergrau commented
@jwelker110 not at all - pushed the update...

2020-03-23 14:46 UTC, jwelker110 approved these changes
Awesome! Thank you!

2020-03-23 14:48 UTC, merged

2020-03-23 17:03 UTC, petergrau commented
@jwelker110 do you actually plan to publish your plugin to npm? that would be quite handy because then we don't nee to include the repo directly...